//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waste_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cleanup_providers
    {
        public int cleanid { get; set; }
        public string Companyname { get; set; }
        public string locality { get; set; }
    }
}
